#!/bin/bash

export UID=$(id -u)
export GID=$(id -g)

IMAGE="publiocavalcante/php82-laravel"

docker build --build-arg UID="${UID}" \
  --build-arg GID="${GID}" \
  -t $IMAGE \
  . \
  --no-cache

docker push $IMAGE

