#!/bin/sh
set -e

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}
VENDOR=/var/www/html/vendor

if [ ! -d "$VENDOR" ]; then
    echo "You need to install vendors in the app"
    tail -f /dev/null
else
  chmod -R 755 /var/www/html/storage*
  chmod -R 755 /var/www/html/bootstrap/cache*

  if [ "$env" != "local" ]; then
    echo "Caching configuration..."
    (cd /var/www/html && php artisan optimize:clear && php artisan optimize)
  fi

  if [ "$env" = "local" ] && [ "$role" = "app" ]; then
    exec supervisord -c /etc/supervisor.d/supervisord.ini
  #  php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
  fi

  if [ "$env" != "local" ] && [ "$role" = "app" ]; then

    exec supervisord -c /etc/supervisor.d/supervisord.ini

  elif [ "$role" = "queue" ]; then

    echo "Running the queue..."
    php /var/www/html/artisan queue:work --verbose --tries=3 --timeout=90

  elif [ "$role" = "scheduler" ]; then

    while [ true ]; do
      php /var/www/html/artisan schedule:run --verbose --no-interaction &
      sleep 60
    done

  elif [ "$role" = "reverb" ]; then

    while [ true ]; do
      php /var/www/html/artisan reverb:start
    done

  else
    echo "Could not match the container role \"$role\""
    exit 1
  fi

fi
